# Generated by Django 2.1 on 2020-05-02 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemp',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
